'dnn17/hist_array_dnn_SingleElectron2017B_Ch1.root':
  type: data
  pretty-name: 'SingleElectron2017B'
  marker-size: 0.6
  group: GData

'dnn17/hist_array_dnn_SingleMuon2017B_Ch0.root':
  type: data
  pretty-name: 'SingleMuon2017B'
  marker-size: 0.6
  group: GData

'dnn17/hist_array_dnn_SingleElectron2017C_Ch1.root':
  type: data
  pretty-name: 'SingleElectron2017C'
  marker-size: 0.6
  group: GData

'dnn17/hist_array_dnn_SingleMuon2017C_Ch0.root':
  type: data
  pretty-name: 'SingleMuon2017C'
  marker-size: 0.6
  group: GData

'dnn17/hist_array_dnn_SingleElectron2017D_Ch1.root':
  type: data
  pretty-name: 'SingleElectron2017D'
  marker-size: 0.6
  group: GData

'dnn17/hist_array_dnn_SingleElectron2017E_Ch1.root':
  type: data
  pretty-name: 'SingleElectron2017E'
  marker-size: 0.6
  group: GData

'dnn17/hist_array_dnn_SingleMuon2017D_Ch0.root':
  type: data
  pretty-name: 'SingleMuon2017D'
  marker-size: 0.6
  group: GData

'dnn17/hist_array_dnn_SingleElectron2017F_Ch1.root':
  type: data
  pretty-name: 'SingleElectron2017F'
  marker-size: 0.6
  group: GData

'dnn17/hist_array_dnn_SingleMuon2017E_Ch0.root':
  type: data
  pretty-name: 'SingleMuon2017E'
  marker-size: 0.6
  group: GData

'dnn17/hist_array_dnn_SingleMuon2017F_Ch0.root':
  type: data
  pretty-name: 'SingleMuon2017F'
  marker-size: 0.6
  group: GData

#'dnn17/hist_array_dnn_TTToSemiLeptonic_ttbb_Ch0.root':
#  type: mc
#  pretty-name: 'TTToSemiLeptonic_ttbb'
#  cross-section: 365.34
#  fill-color: '#330000'
#  group: Gttbb
#  order: 0
#  generated-events: 43379133.0
#
#'dnn17/hist_array_dnn_TTToSemiLeptonic_ttbj_Ch0.root':
#  type: mc
#  pretty-name: 'TTToSemiLeptonic_ttbj'
#  cross-section: 365.34
#  fill-color: '#660000'
#  group: Gttbj
#  order: 1
#  generated-events: 43379133.0
#
#'dnn17/hist_array_dnn_TTToSemiLeptonic_ttcc_Ch0.root':
#  type: mc
#  pretty-name: 'TTToSemiLeptonic_ttcc'
#  cross-section: 365.34
#  fill-color: '#990000'
#  group: Gttcc
#  order: 2
#  generated-events: 43379133.0
#
#'dnn17/hist_array_dnn_TTToSemiLeptonic_ttother_Ch0.root':
#  type: mc
#  pretty-name: 'TTToSemiLeptonic_ttother'
#  cross-section: 365.34
#  fill-color: '#ff6666'
#  group: GttBkg
#  order: 4
#  generated-events: 43379133.0
#
'dnn17/hist_array_dnn_TTToSemiLeptonic_PSweight_ttbb_Ch0.root':
  type: mc
  pretty-name: 'TTToSemiLeptonic_PSweight_ttbb'
  cross-section: 365.34
  fill-color: '#330000'
  group: Gttbb
  order: 0
  generated-events: 109124472.0

'dnn17/hist_array_dnn_TTToSemiLeptonic_PSweight_ttbj_Ch0.root':
  type: mc
  pretty-name: 'TTToSemiLeptonic_PSweight_ttbj'
  cross-section: 365.34
  fill-color: '#660000'
  group: Gttbj
  order: 1
  generated-events: 109124472.0

'dnn17/hist_array_dnn_TTToSemiLeptonic_PSweight_ttcc_Ch0.root':
  type: mc
  pretty-name: 'TTToSemiLeptonic_PSweight_ttcc'
  cross-section: 365.34
  fill-color: '#990000'
  group: Gttcc
  order: 2
  generated-events: 109124472.0

'dnn17/hist_array_dnn_TTToSemiLeptonic_PSweight_ttother_Ch0.root':
  type: mc
  pretty-name: 'TTToSemiLeptonic_PSweight_ttother'
  cross-section: 365.34
  fill-color: '#ff6666'
  group: GttBkg
  order: 4
  generated-events: 109124472.0

'dnn17/hist_array_dnn_TTTo2L2Nu_Ch0.root':
  type: mc
  pretty-name: 'TTTo2L2Nu'
  cross-section: 88.29
  fill-color: '#ff6666'
  group: GttBkg
  order: 5
  generated-events: 8926992.0

'dnn17/hist_array_dnn_TTToHadronic_Ch0.root':
  type: mc
  pretty-name: 'TTToHadronic'
  cross-section: 377.96
  fill-color: '#ff6666'
  group: GttBkg
  order: 7
  generated-events: 41729120.0

'dnn17/hist_array_dnn_DYJetsToLL_M-10to50_Ch0.root':
  type: mc
  pretty-name: 'DYJetsToLL_M-10to50'
  cross-section: 18610.0
  fill-color: '#000099'
  group: GVJets
  order: 23
  generated-events: 79310821.0

'dnn17/hist_array_dnn_DYJetsToLL_M-50-amcatnloFXFX_Ch0.root':
  type: mc
  pretty-name: 'DYJetsToLL_M-50-amcatnloFXFX'
  cross-section: 6077.22
  fill-color: '#000099'
  group: GVJets
  order: 22
  generated-events: 142142566.0

'dnn17/hist_array_dnn_ST_s-channel_4f_leptonDecays_Ch0.root':
  type: mc
  pretty-name: 'ST_s-channel_4f_leptonDecays'
  cross-section: 3.36
  fill-color: '#990099'
  group: GSingleT
  order: 16
  generated-events: 6185062.0

'dnn17/hist_array_dnn_ST_t-channel_antitop_Ch0.root':
  type: mc
  pretty-name: 'ST_t-channel_antitop'
  cross-section: 80.95
  fill-color: '#990099'
  group: GSingleT
  order: 17
  generated-events: 64722800.0

'dnn17/hist_array_dnn_ST_t-channel_top_Ch0.root':
  type: mc
  pretty-name: 'ST_t-channel_top'
  cross-section: 136.02
  fill-color: '#990099'
  group: GSingleT
  order: 14
  generated-events: 120960200.0

'dnn17/hist_array_dnn_ST_tW_antitop_Ch0.root':
  type: mc
  pretty-name: 'ST_tW_antitop'
  cross-section: 35.85
  fill-color: '#990099'
  group: GSingleT
  order: 18
  generated-events: 7916640.0

'dnn17/hist_array_dnn_ST_tW_top_Ch0.root':
  type: mc
  pretty-name: 'ST_tW_top'
  cross-section: 35.85
  fill-color: '#990099'
  group: GSingleT
  order: 15
  generated-events: 7734344.0

'dnn17/hist_array_dnn_TTWJetsToLNu_Ch0.root':
  type: mc
  pretty-name: 'TTWJetsToLNu'
  cross-section: 0.2043
  fill-color: '#ff66ff'
  group: GttX
  order: 11
  generated-events: 5290549.0

'dnn17/hist_array_dnn_TTWJetsToQQ_Ch0.root':
  type: mc
  pretty-name: 'TTWJetsToQQ'
  cross-section: 0.4062
  fill-color: '#ff66ff'
  group: GttX
  order: 10
  generated-events: 441560.0

'dnn17/hist_array_dnn_TTZToLLNuNu_M-10_Ch0.root':
  type: mc
  pretty-name: 'TTZToLLNuNu_M-10'
  cross-section: 0.2529
  fill-color: '#ff66ff'
  group: GttX
  order: 13
  generated-events: 3745298.0

'dnn17/hist_array_dnn_TTZToQQ_TuneCP5_13TeV_Ch0.root':
  type: mc
  pretty-name: 'TTZToQQ_TuneCP5_13TeV'
  cross-section: 0.5297
  fill-color: '#ff66ff'
  group: GttX
  order: 12
  generated-events: 356286.0

'dnn17/hist_array_dnn_ttHToNonbb_Ch0.root':
  type: mc
  pretty-name: 'ttHToNonbb'
  cross-section: 0.2151
  fill-color: '#ff66ff'
  group: GttH
  order: 9
  generated-events: 7814711.0

'dnn17/hist_array_dnn_ttHTobb_Ch0.root':
  type: mc
  pretty-name: 'ttHTobb'
  cross-section: 0.2934
  fill-color: '#ff66ff'
  group: GttH
  order: 8
  generated-events: 7833734.0

'dnn17/hist_array_dnn_WWTo2L2Nu_Ch0.root':
  type: mc
  pretty-name: 'WWTo2L2Nu'
  cross-section: 12.178
  fill-color: '#00cccc'
  group: GVV
  order: 19
  generated-events: 1992522.0

'dnn17/hist_array_dnn_WWToLNuQQ_Ch0.root':
  type: mc
  pretty-name: 'WWToLNuQQ'
  cross-section: 49.997
  fill-color: '#00cccc'
  group: GVV
  order: 19
  generated-events: 18705936.0

'dnn17/hist_array_dnn_WZTo2L2Q_Ch0.root':
  type: mc
  pretty-name: 'WZTo2L2Q'
  cross-section: 5.595
  fill-color: '#00cccc'
  group: GVV
  order: 20
  generated-events: 16664610.0

'dnn17/hist_array_dnn_WZTo3LNu_Ch0.root':
  type: mc
  pretty-name: 'WZTo3LNu'
  cross-section: 4.42965
  fill-color: '#00cccc'
  group: GVV
  order: 20
  generated-events: 6887413.0

'dnn17/hist_array_dnn_ZZTo2L2Q_Ch0.root':
  type: mc
  pretty-name: 'ZZTo2L2Q'
  cross-section: 3.22
  fill-color: '#00cccc'
  group: GVV
  order: 21
  generated-events: 17768294.0

'dnn17/hist_array_dnn_W1JetsToLNu_Ch0.root':
  type: mc
  pretty-name: 'W1JetsToLNu'
  cross-section: 9625
  fill-color: '#ff9933'
  group: GVJets
  order: 24
  generated-events: 45268918.0

'dnn17/hist_array_dnn_W2JetsToLNu_Ch0.root':
  type: mc
  pretty-name: 'W2JetsToLNu'
  cross-section: 2793
  fill-color: '#ff9933'
  group: GVJets
  order: 25
  generated-events: 38903855.0

'dnn17/hist_array_dnn_W3JetsToLNu_Ch0.root':
  type: mc
  pretty-name: 'W3JetsToLNu'
  cross-section: 992.5
  fill-color: '#ff9933'
  group: GVJets
  order: 26
  generated-events: 19669693.0

'dnn17/hist_array_dnn_W4JetsToLNu_Ch0.root':
  type: mc
  pretty-name: 'W4JetsToLNu'
  cross-section: 544.3
  fill-color: '#ff9933'
  group: GVJets
  order: 27
  generated-events: 11074019.0

#'dnn17/hist_array_dnn_TTToSemiLeptonic_ttbb_Ch1.root':
#  type: mc
#  pretty-name: 'TTToSemiLeptonic_ttbb'
#  cross-section: 365.34
#  fill-color: '#330000'
#  group: Gttbb
#  order: 0
#  generated-events: 43379133.0
#
#'dnn17/hist_array_dnn_TTToSemiLeptonic_ttbj_Ch1.root':
#  type: mc
#  pretty-name: 'TTToSemiLeptonic_ttbj'
#  cross-section: 365.34
#  fill-color: '#660000'
#  group: Gttbj
#  order: 1
#  generated-events: 43379133.0
#
#'dnn17/hist_array_dnn_TTToSemiLeptonic_ttcc_Ch1.root':
#  type: mc
#  pretty-name: 'TTToSemiLeptonic_ttcc'
#  cross-section: 365.34
#  fill-color: '#990000'
#  group: Gttcc
#  order: 2
#  generated-events: 43379133.0
#
#'dnn17/hist_array_dnn_TTToSemiLeptonic_ttother_Ch1.root':
#  type: mc
#  pretty-name: 'TTToSemiLeptonic_ttother'
#  cross-section: 365.34
#  fill-color: '#ff6666'
#  group: GttBkg
#  order: 4
#  generated-events: 43379133.0
#
'dnn17/hist_array_dnn_TTToSemiLeptonic_PSweight_ttbb_Ch1.root':
  type: mc
  pretty-name: 'TTToSemiLeptonic_PSweight_ttbb'
  cross-section: 365.34
  fill-color: '#330000'
  group: Gttbb
  order: 0
  generated-events: 109124472.0

'dnn17/hist_array_dnn_TTToSemiLeptonic_PSweight_ttbj_Ch1.root':
  type: mc
  pretty-name: 'TTToSemiLeptonic_PSweight_ttbj'
  cross-section: 365.34
  fill-color: '#660000'
  group: Gttbj
  order: 1
  generated-events: 109124472.0

'dnn17/hist_array_dnn_TTToSemiLeptonic_PSweight_ttcc_Ch1.root':
  type: mc
  pretty-name: 'TTToSemiLeptonic_PSweight_ttcc'
  cross-section: 365.34
  fill-color: '#990000'
  group: Gttcc
  order: 2
  generated-events: 109124472.0

'dnn17/hist_array_dnn_TTToSemiLeptonic_PSweight_ttother_Ch1.root':
  type: mc
  pretty-name: 'TTToSemiLeptonic_PSweight_ttother'
  cross-section: 365.34
  fill-color: '#ff6666'
  group: GttBkg
  order: 4
  generated-events: 109124472.0

'dnn17/hist_array_dnn_TTTo2L2Nu_Ch1.root':
  type: mc
  pretty-name: 'TTTo2L2Nu'
  cross-section: 88.29
  fill-color: '#ff6666'
  group: GttBkg
  order: 5
  generated-events: 8926992.0

'dnn17/hist_array_dnn_TTToHadronic_Ch1.root':
  type: mc
  pretty-name: 'TTToHadronic'
  cross-section: 377.96
  fill-color: '#ff6666'
  group: GttBkg
  order: 7
  generated-events: 41729120.0

'dnn17/hist_array_dnn_DYJetsToLL_M-10to50_Ch1.root':
  type: mc
  pretty-name: 'DYJetsToLL_M-10to50'
  cross-section: 18610.0
  fill-color: '#000099'
  group: GVJets
  order: 23
  generated-events: 79310821.0

'dnn17/hist_array_dnn_DYJetsToLL_M-50-amcatnloFXFX_Ch1.root':
  type: mc
  pretty-name: 'DYJetsToLL_M-50-amcatnloFXFX'
  cross-section: 6077.22
  fill-color: '#000099'
  group: GVJets
  order: 22
  generated-events: 142142566.0

'dnn17/hist_array_dnn_ST_s-channel_4f_leptonDecays_Ch1.root':
  type: mc
  pretty-name: 'ST_s-channel_4f_leptonDecays'
  cross-section: 3.36
  fill-color: '#990099'
  group: GSingleT
  order: 16
  generated-events: 6185062.0

'dnn17/hist_array_dnn_ST_t-channel_antitop_Ch1.root':
  type: mc
  pretty-name: 'ST_t-channel_antitop'
  cross-section: 80.95
  fill-color: '#990099'
  group: GSingleT
  order: 17
  generated-events: 64722800.0

'dnn17/hist_array_dnn_ST_t-channel_top_Ch1.root':
  type: mc
  pretty-name: 'ST_t-channel_top'
  cross-section: 136.02
  fill-color: '#990099'
  group: GSingleT
  order: 14
  generated-events: 120960200.0

'dnn17/hist_array_dnn_ST_tW_antitop_Ch1.root':
  type: mc
  pretty-name: 'ST_tW_antitop'
  cross-section: 35.85
  fill-color: '#990099'
  group: GSingleT
  order: 18
  generated-events: 7916640.0

'dnn17/hist_array_dnn_ST_tW_top_Ch1.root':
  type: mc
  pretty-name: 'ST_tW_top'
  cross-section: 35.85
  fill-color: '#990099'
  group: GSingleT
  order: 15
  generated-events: 7734344.0

'dnn17/hist_array_dnn_TTWJetsToLNu_Ch1.root':
  type: mc
  pretty-name: 'TTWJetsToLNu'
  cross-section: 0.2043
  fill-color: '#ff66ff'
  group: GttX
  order: 11
  generated-events: 5290549.0

'dnn17/hist_array_dnn_TTWJetsToQQ_Ch1.root':
  type: mc
  pretty-name: 'TTWJetsToQQ'
  cross-section: 0.4062
  fill-color: '#ff66ff'
  group: GttX
  order: 10
  generated-events: 441560.0

'dnn17/hist_array_dnn_TTZToLLNuNu_M-10_Ch1.root':
  type: mc
  pretty-name: 'TTZToLLNuNu_M-10'
  cross-section: 0.2529
  fill-color: '#ff66ff'
  group: GttX
  order: 13
  generated-events: 3745298.0

'dnn17/hist_array_dnn_TTZToQQ_TuneCP5_13TeV_Ch1.root':
  type: mc
  pretty-name: 'TTZToQQ_TuneCP5_13TeV'
  cross-section: 0.5297
  fill-color: '#ff66ff'
  group: GttX
  order: 12
  generated-events: 356286.0

'dnn17/hist_array_dnn_ttHToNonbb_Ch1.root':
  type: mc
  pretty-name: 'ttHToNonbb'
  cross-section: 0.2151
  fill-color: '#ff66ff'
  group: GttH
  order: 9
  generated-events: 7814711.0

'dnn17/hist_array_dnn_ttHTobb_Ch1.root':
  type: mc
  pretty-name: 'ttHTobb'
  cross-section: 0.2934
  fill-color: '#ff66ff'
  group: GttH
  order: 8
  generated-events: 7833734.0

'dnn17/hist_array_dnn_WWTo2L2Nu_Ch1.root':
  type: mc
  pretty-name: 'WWTo2L2Nu'
  cross-section: 12.178
  fill-color: '#00cccc'
  group: GVV
  order: 19
  generated-events: 1992522.0

'dnn17/hist_array_dnn_WWToLNuQQ_Ch1.root':
  type: mc
  pretty-name: 'WWToLNuQQ'
  cross-section: 49.997
  fill-color: '#00cccc'
  group: GVV
  order: 19
  generated-events: 18705936.0

'dnn17/hist_array_dnn_WZTo2L2Q_Ch1.root':
  type: mc
  pretty-name: 'WZTo2L2Q'
  cross-section: 5.595
  fill-color: '#00cccc'
  group: GVV
  order: 20
  generated-events: 16664610.0

'dnn17/hist_array_dnn_WZTo3LNu_Ch1.root':
  type: mc
  pretty-name: 'WZTo3LNu'
  cross-section: 4.42965
  fill-color: '#00cccc'
  group: GVV
  order: 20
  generated-events: 6887413.0

'dnn17/hist_array_dnn_ZZTo2L2Q_Ch1.root':
  type: mc
  pretty-name: 'ZZTo2L2Q'
  cross-section: 3.22
  fill-color: '#00cccc'
  group: GVV
  order: 21
  generated-events: 17768294.0

'dnn17/hist_array_dnn_W1JetsToLNu_Ch1.root':
  type: mc
  pretty-name: 'W1JetsToLNu'
  cross-section: 9625
  fill-color: '#ff9933'
  group: GVJets
  order: 24
  generated-events: 45268918.0

'dnn17/hist_array_dnn_W2JetsToLNu_Ch1.root':
  type: mc
  pretty-name: 'W2JetsToLNu'
  cross-section: 2793
  fill-color: '#ff9933'
  group: GVJets
  order: 25
  generated-events: 38903855.0

'dnn17/hist_array_dnn_W3JetsToLNu_Ch1.root':
  type: mc
  pretty-name: 'W3JetsToLNu'
  cross-section: 992.5
  fill-color: '#ff9933'
  group: GVJets
  order: 26
  generated-events: 19669693.0

'dnn17/hist_array_dnn_W4JetsToLNu_Ch1.root':
  type: mc
  pretty-name: 'W4JetsToLNu'
  cross-section: 544.3
  fill-color: '#ff9933'
  group: GVJets
  order: 27
  generated-events: 11074019.0
