GData:
  legend: 'Data'
  marker-size: 0.6
GWJets:
  fill-color: '#ff9933'
  line-color: '1'
  legend: 'WJets'
GttBkg:
  fill-color: '#ff6666'
  line-color: '1'
  legend: 'ttBkg'
GttX:
  fill-color: '#ff66ff'
  line-color: '1'
  legend: 'ttX'
GZJets:
  fill-color: '#000099'
  line-color: '1'
  legend: 'ZJets'
GSingleT:
  fill-color: '#990099'
  line-color: '1'
  legend: 'SingleT'
GVV:
  fill-color: '#00cccc'
  line-color: '1'
  legend: 'VV'
GQCD:
  fill-color: '#d0cfd4'
  line-color: '1'
  legend: 'QCD'
Gttbb:
  fill-color: '#330000'
  line-color: '1'
  legend: 'ttbb'
Gttbj:
  fill-color: '#660000'
  line-color: '1'
  legend: 'ttbj'
Gttcc:
  fill-color: '#990000'
  line-color: '1'
  legend: 'ttcc'
GttLF:
  fill-color: '#cc0000'
  line-color: '1'
  legend: 'ttLF'
