'h_njets_S0':
  x-axis: "Jet multiplicity"
  y-axis: "Events"
  y-axis-format: "%1%"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_lepton_pt_S0':
  x-axis: "Lepton p_{T} (GeV)" 
  y-axis: "Events"
  y-axis-format: "%1% / %2$.1f GeV"
  save-extensions: ['pdf']
  show-ratio: true
  #for-yields: true
  log-y: true
  #yields-table-order: 0
  #yields-title: '$S0'

'h_lepton_eta_S0':
  x-axis: "Lepton ||#eta||"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_lepton_phi_S0':
  x-axis: "Lepton #phi"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_njets_S1':
  x-axis: "Jet multiplicity"
  y-axis: "Events"
  y-axis-format: "%1%"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_lepton_pt_S1':
  x-axis: "Lepton p_{T} (GeV)" 
  y-axis: "Events"
  y-axis-format: "%1% / %2$.1f GeV"
  save-extensions: ['pdf']
  show-ratio: true
#  for-yields: true
  log-y: true
#  yields-table-order: 0
#  yields-title: '1l 1j'

'h_lepton_eta_S1':
  x-axis: "Lepton |#eta|"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_lepton_phi_S1':
  x-axis: "Lepton #phi"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_njets_S2':
  x-axis: "Jet multiplicity"
  y-axis: "Events"
  y-axis-format: "%1%"
  save-extensions: ['pdf']
  log-y: true
  show-ratio: true

'h_nbjets_S2':
  x-axis: "b Jet multiplicity"
  y-axis: "Events"
  y-axis-format: "%1%"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_lepton_pt_S2':
  x-axis: "Lepton p_{T} (GeV)" 
  y-axis: "Events"
  y-axis-format: "%1% / %2$.1f GeV"
  save-extensions: ['pdf']
  show-ratio: true
  for-yields: true
  log-y: true
  yields-table-order: 0
  yields-title: '1l 4j 2b'

'h_lepton_eta_S2':
  x-axis: "Lepton |#eta|"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_lepton_phi_S2':
  x-axis: "Lepton #phi"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet1_pt_S2':
  x-axis: "Leading Jet p_{T}"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.1f GeV"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet1_eta_S2':
  x-axis: "Leading Jet |#eta|"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet2_pt_S2':
  x-axis: "Subleading Jet p_{T}"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.1f GeV"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet2_eta_S2':
  x-axis: "Subleading Jet |#eta|"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet3_pt_S2':
  y-axis-format: '%1% / %2$.1f GeV'
  x-axis: "3^{rd} Jet p_{T}"
  y-axis: "Events"
  #y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet3_eta_S2':
  x-axis: "3^{rd} Jet |#eta|"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet4_pt_S2':
  y-axis-format: '%1% / %2$.1f GeV'
  x-axis: "4^{th} Jet p_{T}"
  y-axis: "Events"
  #y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet4_eta_S2':
  x-axis: "4^{th} Jet |#eta|"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_nbjets_S3':
  x-axis: "b Jet multiplicity"
  y-axis: "Events"
  y-axis-format: "%1%"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_lepton_pt_S3':
  x-axis: "Lepton p_{T} (GeV)" 
  y-axis: "Events"
  y-axis-format: "%1% / %2$.1f GeV"
  save-extensions: ['pdf']
  show-ratio: true
  for-yields: true
  log-y: true
  yields-table-order: 1
  yields-title: '1l 6j 2b'

'h_lepton_eta_S3':
  x-axis: "Lepton |#eta|"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_lepton_phi_S3':
  x-axis: "Lepton #phi"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet1_pt_S3':
  x-axis: "Leading Jet p_{T}"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.1f GeV"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet1_eta_S3':
  x-axis: "Leading Jet |#eta|"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet2_pt_S3':
  x-axis: "Subleading Jet p_{T}"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.1f GeV"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet2_eta_S3':
  x-axis: "Subleading Jet |#eta|"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet3_pt_S3':
  y-axis-format: '%1% / %2$.1f GeV'
  x-axis: "3^{rd} Jet p_{T}"
  y-axis: "Events"
  #y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet3_eta_S3':
  x-axis: "3^{rd} Jet |#eta|"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet4_pt_S3':
  y-axis-format: '%1% / %2$.1f GeV'
  x-axis: "4^{th} Jet p_{T}"
  y-axis: "Events"
  #y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_jet4_eta_S3':
  x-axis: "4^{th} Jet |#eta|"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_lepton_pt_S4':
  x-axis: "Lepton p_{T} (GeV)" 
  y-axis: "Events"
  y-axis-format: "%1% / %2$.1f GeV"
  save-extensions: ['pdf']
  show-ratio: true
  for-yields: true
  log-y: true
  yields-table-order: 2
  yields-title: '1l 6j 4b'

'h_lepton_eta_S4':
  x-axis: "Lepton |#eta|"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_lepton_phi_S4':
  x-axis: "Lepton #phi"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_bjet1_pt_S4':
  x-axis: "Leading b-Jet p_{T}"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_bjet2_pt_S4':
  x-axis: "Subleading b-Jet p_{T}"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_minMass_S4':
  x-axis: "M_{b#bar{b}}"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.1f GeV"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true

'h_mindR_S4':
  x-axis: "#DeltaR_{b#bar{b}}"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  #log-y: true
  show-ratio: true
